app/models.py
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, login

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class Transaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    amount = db.Column(db.Float, nullable=False)
    category = db.Column(db.String(64))
    date = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Budget(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(64))
    amount = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class SavingsGoal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    goal = db.Column(db.String(64))
    amount = db.Column(db.Float, nullable=False)
    current_amount = db.Column(db.Float, default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, FloatField, IntegerField, DecimalField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo, NumberRange
from .models import User



class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

class TransactionForm(FlaskForm):
    amount = FloatField('Amount', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField('Add Transaction')
    
class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Current Password', validators=[DataRequired()])
    new_password = PasswordField('New Password', validators=[DataRequired()])
    confirm_new_password = PasswordField('Confirm New Password', validators=[DataRequired(), EqualTo('new_password')])
    submit = SubmitField('Change Password')


class EditTransactionForm(FlaskForm):
    amount = DecimalField('Amount', validators=[DataRequired(), NumberRange(min=0)])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField('Update Transaction')
    
class EditBudgetForm(FlaskForm):
    category = StringField('Category', validators=[DataRequired()])
    amount = DecimalField('Amount', validators=[DataRequired(), NumberRange(min=0)])
    submit = SubmitField('Update Budget')
    
class EditSavingsGoalForm(FlaskForm):
    goal = StringField('Goal', validators=[DataRequired()])
    amount = DecimalField('Amount', validators=[DataRequired(), NumberRange(min=0)])
    current_amount = DecimalField('Current Amount', validators=[DataRequired(), NumberRange(min=0)])
    submit = SubmitField('Update Savings Goal')
    
class BudgetForm(FlaskForm):
    category = StringField('Category', validators=[DataRequired()])
    amount = FloatField('Amount', validators=[DataRequired(), NumberRange(min=0)])
    submit = SubmitField('Add Budget')

class SavingsGoalForm(FlaskForm):
    goal = StringField('Goal', validators=[DataRequired()])
    amount = IntegerField('Amount', validators=[DataRequired()])
    submit = SubmitField('Add Goal')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect
from config import Config


db = SQLAlchemy()
login = LoginManager()
csrf = CSRFProtect()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login.init_app(app)
    csrf.init_app(app)
    
    from .routes import main_bp
    from .user_routes import user_bp
    from .transaction_routes import transaction_bp
    from .budget_routes import budget_bp
    from .savings_goal_routes import savings_goal_bp
    app.register_blueprint(main_bp, url_prefix='/')
    app.register_blueprint(user_bp, url_prefix='/users')
    app.register_blueprint(transaction_bp, url_prefix='/transactions')
    app.register_blueprint(budget_bp, url_prefix='/budgets')
    app.register_blueprint(savings_goal_bp, url_prefix='/savings_goals')
    
    return app

app/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from .models import Transaction, Budget, SavingsGoal

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def homepage():
    return render_template('homepage.html')

@main_bp.route('/index')
@login_required
def index():
    transactions = Transaction.query.filter_by(user_id=current_user.id).all()
    budgets = Budget.query.filter_by(user_id=current_user.id).all()
    savings_goals = SavingsGoal.query.filter_by(user_id=current_user.id).all()
    total_transactions_amount = sum(transaction.amount for transaction in transactions)
    
    return render_template('index.html', transactions=transactions, budgets=budgets, savings_goals=savings_goals, total_transactions_amount=total_transactions_amount)

app/templates/add_budget.html
{% extends 'base.html' %}

{% block title %}Add Budget{% endblock %}

{% block content %}
<div class="max-w-sm h-screen mt-5">
    <h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-2xl dark:text-white">Add Budget</h1>
    <form action="{{ url_for('budget.add_budget') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="mb-1">
            {{ form.category.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
            {{ form.category(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500")}}
            {% for error in form.category.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mb-1">
            {{ form.amount.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
            {{ form.amount(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500")}}
            {% for error in form.amount.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mb-1">
            <p> {{ form.submit(class="text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800") }}</p>
           
        </div>
    </form>
</div>

{% endblock %}

app/templates/add_savings_goal.html
{% extends 'base.html' %}

{% block title %}Add Savings Goal{% endblock %}

{% block content %}
<div class="max-w-sm h-screen mt-5">
    <h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-2xl dark:text-white">Add Savings Goal</h1>
    <form action="{{ url_for('savings_goal.add_savings_goal') }}" method="post">
        {{ form.hidden_tag() }}
        <div class="mb-1">
            {{ form.goal.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
            {{ form.goal(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500") }}
            {% for error in form.goal.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mb-1">
            {{ form.amount.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
            {{ form.amount(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500") }}
            {% for error in form.amount.errors %}
                <span class="error">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="mb-1">
            <p> {{ form.submit(class="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800") }}</p>
        </div>
    </form>
</div>

{% endblock %}

app/templates/add_transaction.html
{% extends 'base.html' %} {% block title %}Add Transaction{% endblock %} {%
block content %}
<div class="max-w-sm h-screen mt-5">
    <h1 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-2xl dark:text-white">Add Transaction</h1>
    <form action="{{ url_for('transaction.add_transaction') }}" method="post">
      {{ form.hidden_tag() }}
      <div class="mb-1">
        {{ form.amount.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }} 
        {{ form.amount(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500")}} 
        
        {% for error in form.amount.errors
        %}
        <span class="error">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="mb-1">
        {{ form.category.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }} {{ form.category(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500")}} {% for error
        in form.category.errors %}
        <span class="error">[{{ error }}]</span
        >
        {% endfor %}
      </div>
    
      <div class="mb-1">
        <p>{{ form.submit(class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800") }}</p>
      </div>
    </form>
</div>



{% endblock %}

app/templates/base_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Vivid Fin{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css">
</head>

<body>


    <nav class="bg-white border-gray-200 dark:bg-gray-900">
        <div
          class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
        >
          <a
            href="{{ url_for('main.homepage') }}"
            class="flex items-center space-x-3 rtl:space-x-reverse"
          >
            <img
              src="../static/assets/logo.png"
              class="h-10"
              alt="Logo"
            />
            <span
              class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"
              >Vivid Fin</span
            >
          </a>
          <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <a
              href="{{ url_for('user.login') }}"
              class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
              >Get Started</a
            >
  
            <button
              data-collapse-toggle="navbar-cta"
              type="button"
              class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
              aria-controls="navbar-cta"
              aria-expanded="false"
            >
              <span class="sr-only">Open main menu</span>
              <svg
                class="w-5 h-5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 17 14"
              >
                <path
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M1 1h15M1 7h15M1 13h15"
                />
              </svg>
            </button>
          </div>
          <div
            class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1"
            id="navbar-cta"
          >
            <ul
              class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
            >
              <li></li>
           
  
              <a
                href="{{ url_for('user.register') }}"
                class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
              ></a>
            </ul>
          </div>
        </div>
      </nav>  
    <!-- <header>
        <nav>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('main.index') }}">Home</a>
                <a href="{{ url_for('transaction.add_transaction') }}">Add Transaction</a>
                <a href="{{ url_for('budget.add_budget') }}">Add Budget</a>
                <a href="{{ url_for('savings_goal.add_savings_goal') }}">Add Savings Goal</a>
                <a href="{{ url_for('user.logout') }}">Logout</a>
            {% else %}
                <a href="{{ url_for('user.login') }}">Login</a>
                <a href="{{ url_for('user.register') }}">Register</a>
            {% endif %}
        </nav>
    </header> -->
    <main >
        {% block content %}{% endblock %}
    </main>

    <footer class="bg-white rounded-lg shadow dark:bg-gray-900 m-4 ">
      <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
          <div class="sm:flex sm:items-center sm:justify-between">
              <a href="{{ url_for('main.homepage') }}" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                  <img src="../static/assets/logo.png" class="h-8" alt="Logo" />
                  <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Vivid Fin</span>
              </a>
              <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
                  <li>
                      <a href="https://github.com/VitaliyV22" class="hover:underline me-4 md:me-6">GitHub</a>
                  </li>
                 
              </ul>
          </div>
          <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
          <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">Vivid Fin 2024 <a href="https://flowbite.com/" class="hover:underline"></a>
      </div>
    </footer>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
 

</body>

</html>

app/templates/edit_budget.html
{% extends "base.html" %} {% block title %}Edit Budget{% endblock %} {% block
content %}
<div class="max-w-sm h-screen">
  <h1
    class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-2xl dark:text-white"
  >
    Edit Transaction
  </h1>
  <form
    action="{{ url_for('budget.edit_budget', budget_id=budget_id) }}"
    method="post"
  >
    {{ form.hidden_tag() }}
    <div class="mb-1">
      {{ form.amount.label(class_="block mb-2 text-sm font-medium text-gray-900
      dark:text-white") }} {{ form.amount(class="form-control bg-gray-50 border
      border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500
      focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700
      dark:border-gray-600 dark:placeholder-gray-400 dark:text-white
      dark:focus:ring-purple-500 dark:focus:border-purple-500")}} {% for error
      in form.amount.errors %}
      <span class="error">[{{ error }}]</span>
      {% endfor %}
    </div>
    <div class="mb-1">
      {{ form.category.label(class_="block mb-2 text-sm font-medium
      text-gray-900 dark:text-white") }} {{ form.category(class="form-control
      bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg
      focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5
      dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400
      dark:text-white dark:focus:ring-purple-500
      dark:focus:border-purple-500")}} {% for error in form.category.errors %}
      <span class="error">[{{ error }}]</span>
      {% endfor %}
    </div>
    <div class="mb-1">
      <p>
        {{ form.submit(class="text-white bg-blue-700 hover:bg-blue-800
        focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium
        rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center
        dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800") }}
      </p>
    </div>
  </form>
</div>

{% endblock %}

app/templates/edit_transaction.html
{% extends "base.html" %} 
{% block title %}Edit Transaction{% endblock %} 
{%block content %}

<div class="max-w-sm h-screen">
  <h1
    class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-2xl dark:text-white"
  >
    Edit Transaction
  </h1>
  <form
  action="{{ url_for('transaction.edit_transaction', transaction_id=transaction_id) }}"
  method="post"
>
  {{ form.hidden_tag() }}
  <div class="mb-1">
    {{ form.amount.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }} 
    {{ form.amount(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500")}} 
    
    {% for error in form.amount.errors
    %}
    <span class="error">[{{ error }}]</span>
    {% endfor %}
  </div>
  <div class="mb-1">
    {{ form.category.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }} 
    {{ form.category(class="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-purple-500 dark:focus:border-purple-500")}} {% for error
    in form.category.errors %}
    <span class="error">[{{ error }}]</span
    >
    {% endfor %}
  </div>
  <div class="mb-1">
    <p>{{ form.submit(class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800") }}</p>
  </div>
</form>
</div> 

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome, {{ current_user.username }}!</h1>

<h2>Transactions</h2>
<ul>
    {% for transaction in transactions %}
        <li>{{ transaction.date }}: {{ transaction.category }} - ${{ transaction.amount }}</li>
    {% endfor %}
</ul>

<h2>Budgets</h2>
<ul>
    {% for budget in budgets %}
        <li>{{ budget.category }}: ${{ budget.amount }}</li>
    {% endfor %}
</ul>

<h2>Savings Goals</h2>
<ul>
    {% for goal in savings_goals %}
        <li>{{ goal.goal }}: ${{ goal.amount }} (Current: ${{ goal.current_amount }})</li>
    {% endfor %}
</ul>

<a href="{{ url_for('transaction.add_transaction') }}">Add Transaction</a>
<a href="{{ url_for('budget.add_budget') }}">Add Budget</a>
<a href="{{ url_for('savings.add_savings_goal') }}">Add Savings Goal</a>
{% endblock %}

app/templates/homepage.html
<!-- homepage.html -->
{% extends "base_2.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}
<body>
<section style="background-position: center; background-repeat: no-repeat; background-image: url('../static/assets/sortter-fbp4D3tU19k-unsplash.jpg'); background-blend-mode: multiply;">
 
  <div class="px-4 mx-auto max-w-screen-xl text-center py-24 lg:py-56">
      <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">A Simple Finance Tracker</h1>
      <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">Track your expenses 📊, budgets 💵 and goals 🏖️</p>
      <div class="flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0">
          <a href="{{ url_for('user.login') }}" class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
              Get started
              <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
          </a>
         
      </div>
  </div>
</section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
  </body>
{% endblock %}

app/templates/register.html
{% extends "base_2.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="max-w-sm mx-auto h-screen mt-5">
<h1 class="mb-5 font-bold text-2xl" >Register</h1>
<form action="{{ url_for('user.register') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-1">
        {{ form.username.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}
        {{ form.username(class_="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}<br>
        {% for error in form.username.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="mb-1">
        {{ form.email.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}<br>
        {{ form.email(class_="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}<br>
        {% for error in form.email.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </div>
    <p>
        {{ form.password.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}<br>
        {{ form.password(class_="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}<br>
        {% for error in form.password.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label(class_="block mb-2 text-sm font-medium text-gray-900 dark:text-white") }}<br>
        {{ form.password2(class_="form-control bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500") }}<br>
        {% for error in form.password2.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </p>
    <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">{{ form.submit() }}</button>
</form>
<p class="py-5">Already a user ? <a class="font-bold" href="{{ url_for('user.login') }}">Login</p>
</div>

{% endblock %}